"""add food_listings and food_requests tables

Revision ID: bd1f31dade9e
Revises: 3aab1ead763b
Create Date: 2026-10-04 17:32:16.930280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd1f31dade9e'
down_revision: Union[str, Sequence[str], None] = '3aab1ead763b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_listings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('donor_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('quantity', sa.String(), nullable=False),
    sa.Column('servings', sa.Integer(), nullable=False),
    sa.Column('expiry_date', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('is_urgent', sa.Boolean(), nullable=False),
    sa.Column('photos', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['donor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_listings_donor_id'), 'food_listings', ['donor_id'], unique=False)
    op.create_table('food_requests',
    sa.Column('request_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('food_listing_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('queue_number', sa.Integer(), nullable=False),
    sa.Column('wait_time_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['food_listing_id'], ['food_listings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_index(op.f('ix_food_requests_food_listing_id'), 'food_requests', ['food_listing_id'], unique=False)
    op.create_index(op.f('ix_food_requests_user_id'), 'food_requests', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_food_requests_user_id'), table_name='food_requests')
    op.drop_index(op.f('ix_food_requests_food_listing_id'), table_name='food_requests')
    op.drop_table('food_requests')
    op.drop_index(op.f('ix_food_listings_donor_id'), table_name='food_listings')
    op.drop_table('food_listings')
    # ### end Alembic commands ###